/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package EclipseGradleJava;

public class Library {
   
    
    public static void main(String[] args) {
		System.out.println("ck");
		System.out.println("first");
	}
    public boolean someLibraryMethod() {
        return true;
    }
}
